-- ============================================================
-- STEP 1 of 3 — tables and security
-- Select all of this file, paste into the Supabase SQL Editor,
-- click Run, and wait for "Success".
-- ============================================================

-- ============================================================================
-- NevadoMedia dashboard — complete database setup
--
-- Paste this WHOLE file into the Supabase SQL Editor and press Run. Once.
--
-- Generated by build-setup.py from the files in migrations/ and seed.sql.
-- Those remain the source of truth; this version has the loops expanded into
-- explicit statements because the SQL editor's statement splitter mishandles
-- dollar-quoted blocks. Do not edit this file by hand.
-- ============================================================================

-- NevadoMedia BI Dashboard — schema
-- Phase 1. Run against a fresh Supabase project, in order, before 0002_rls.sql.


-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------
create type user_role          as enum ('admin', 'operator');
create type payment_status     as enum ('paid', 'pending', 'overdue');
create type ball_side          as enum ('nevadomedia', 'client', 'waiting');
create type content_stage      as enum ('scripted', 'shot', 'edited', 'approved', 'scheduled', 'posted');
create type sales_stage        as enum ('lead', 'setting_call', 'sales_call', 'proposal', 'closed', 'lost');
create type lead_status        as enum ('new', 'qualified', 'disqualified', 'booked', 'closed', 'lost');
create type call_class         as enum ('sales', 'client', 'internal');
create type sync_status        as enum ('running', 'success', 'error');
create type funnel_stage       as enum ('visitor', 'form_started', 'form_completed', 'call_booked', 'call_showed', 'closed');
create type assignment_status  as enum ('pending', 'in_progress', 'delivered', 'overdue');

-- ---------------------------------------------------------------------------
-- updated_at helper
-- ---------------------------------------------------------------------------
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as '
begin
  new.updated_at = now();
  return new;
end;
';

-- ---------------------------------------------------------------------------
-- profiles — one row per auth user, carries the role that RLS keys off
-- ---------------------------------------------------------------------------
create table public.profiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  email       text not null unique,
  full_name   text,
  role        user_role not null default 'operator',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- New signups become operators unless the email is on the admin allowlist.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as '
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> ''full_name'', split_part(new.email, ''@'', 1)),
    -- Both founders hold admin: identical permissions, both see and edit
    -- everything. The operator role remains defined for a future hire.
    case when lower(new.email) in (
           ''sebastian@nevadomedia.info'',
           ''nicolas@nevadomedia.info''
         )
         then ''admin''::user_role
         else ''operator''::user_role
    end
  )
  on conflict (id) do nothing;
  return new;
end;
';



-- ---------------------------------------------------------------------------
-- clients
-- ---------------------------------------------------------------------------
create table public.clients (
  id              uuid primary key default gen_random_uuid(),
  -- unique so the seed and the Stripe/GHL matchers can upsert on name
  name            text not null unique,
  service         text,
  retainer        numeric(10,2) not null default 0,       -- money: admin only
  payment_status  payment_status not null default 'pending',
  payment_status_override boolean not null default false, -- true = manual wins over Stripe
  contract_start  date,
  renewal_date    date,
  last_touchpoint date,
  next_action     text,
  next_action_due date,
  goals           text,
  goal_progress   smallint not null default 0 check (goal_progress between 0 and 100),
  at_risk         boolean not null default false,
  notes           text,
  ball_side       ball_side not null default 'nevadomedia',
  location        text,
  active          boolean not null default true,
  stripe_customer_id text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index on public.clients (active, at_risk);

-- days_until_renewal is derived, never stored.
create or replace function public.days_until_renewal(c public.clients)
returns integer
language sql
stable
as ' select (c.renewal_date - current_date)::int ';

-- ---------------------------------------------------------------------------
-- onboarding_checklist
-- ---------------------------------------------------------------------------
create table public.onboarding_checklist (
  id         uuid primary key default gen_random_uuid(),
  client_id  uuid not null references public.clients(id) on delete cascade,
  item       text not null,
  owner      text,
  completed  boolean not null default false,
  due_date   date,
  sort_order smallint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index on public.onboarding_checklist (client_id, completed);

-- ---------------------------------------------------------------------------
-- content_pipeline
-- ---------------------------------------------------------------------------
create table public.content_pipeline (
  id          uuid primary key default gen_random_uuid(),
  client_id   uuid not null references public.clients(id) on delete cascade,
  title       text not null,
  format      text,
  stage       content_stage not null default 'scripted',
  assigned_to text,
  due_date    date,
  sort_order  integer not null default 0,   -- position inside its kanban column
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index on public.content_pipeline (stage, sort_order);
create index on public.content_pipeline (client_id);

-- ---------------------------------------------------------------------------
-- weekly_metrics
-- ---------------------------------------------------------------------------
create table public.weekly_metrics (
  id                uuid primary key default gen_random_uuid(),
  week_date         date not null unique,          -- Monday of the week
  calls_booked      integer not null default 0,
  show_rate         numeric(5,2),                  -- percent
  close_rate        numeric(5,2),
  revenue           numeric(10,2) not null default 0,
  churn_rate        numeric(5,2),
  outstanding_tasks integer not null default 0,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- expenses
-- ---------------------------------------------------------------------------
create table public.expenses (
  id         uuid primary key default gen_random_uuid(),
  month      date not null,                        -- first of the month
  category   text not null,
  amount     numeric(10,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (month, category)
);

-- ---------------------------------------------------------------------------
-- sales_pipeline
-- ---------------------------------------------------------------------------
create table public.sales_pipeline (
  id              uuid primary key default gen_random_uuid(),
  prospect_name   text not null,
  trade           text,
  location        text,
  monthly_revenue numeric(12,2),
  stage           sales_stage not null default 'lead',
  next_step       text,
  next_step_due   date,
  probability     smallint check (probability between 0 and 100),
  notes           text,
  sort_order      integer not null default 0,
  ghl_opportunity_id text unique,                  -- set by the GHL sync (phase 5)
  ghl_contact_id  text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index on public.sales_pipeline (stage, sort_order);

-- ---------------------------------------------------------------------------
-- team_assignments
-- ---------------------------------------------------------------------------
create table public.team_assignments (
  id             uuid primary key default gen_random_uuid(),
  assignee       text not null,                    -- 'Editor', 'Caleb', ...
  task           text not null,
  client_id      uuid references public.clients(id) on delete set null,
  sent_date      date,
  due_date       date,
  delivered_date date,
  status         assignment_status not null default 'pending',
  payment_amount numeric(10,2),
  payment_status payment_status,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index on public.team_assignments (assignee, status);

-- ---------------------------------------------------------------------------
-- lead_response_log
-- ---------------------------------------------------------------------------
create table public.lead_response_log (
  id                   uuid primary key default gen_random_uuid(),
  lead_name            text not null,
  lead_source          text,
  client_id            uuid references public.clients(id) on delete set null,
  received_at          timestamptz not null,
  first_contacted_at   timestamptz,
  -- generated: minutes between receipt and first contact. Null until contacted.
  response_time_minutes integer generated always as (
    case when first_contacted_at is null then null
         else floor(extract(epoch from (first_contacted_at - received_at)) / 60)::int
    end
  ) stored,
  status               lead_status not null default 'new',
  ghl_contact_id       text unique,
  notes                text,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);
create index on public.lead_response_log (received_at desc);

-- ---------------------------------------------------------------------------
-- client_communication_log
-- ---------------------------------------------------------------------------
create table public.client_communication_log (
  id                  uuid primary key default gen_random_uuid(),
  client_id           uuid not null references public.clients(id) on delete cascade,
  date                date not null default current_date,
  summary             text not null,
  next_followup_date  date,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);
create index on public.client_communication_log (client_id, date desc);

-- ---------------------------------------------------------------------------
-- funnel_events
-- ---------------------------------------------------------------------------
create table public.funnel_events (
  id         uuid primary key default gen_random_uuid(),
  session_id text not null,
  stage      funnel_stage not null,
  field_name text,                                  -- last field touched, for drop-off
  drop_off   boolean not null default false,
  metadata   jsonb not null default '{}'::jsonb,
  timestamp  timestamptz not null default now()
);
create index on public.funnel_events (session_id);
create index on public.funnel_events (stage, timestamp desc);

-- ---------------------------------------------------------------------------
-- ad_accounts — maps a provider account id to a client
-- ---------------------------------------------------------------------------
create table public.ad_accounts (
  id         uuid primary key default gen_random_uuid(),
  client_id  uuid references public.clients(id) on delete set null,
  provider   text not null default 'meta',
  account_id text not null,                         -- 'act_919241897734064'
  label      text not null,
  active     boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, account_id)
);

-- ---------------------------------------------------------------------------
-- meta_insights_daily — one row per ad per day (phase 4)
-- ---------------------------------------------------------------------------
create table public.meta_insights_daily (
  id            uuid primary key default gen_random_uuid(),
  account_id    text not null,
  date          date not null,
  campaign_id   text,
  campaign_name text,
  adset_id      text,
  adset_name    text,
  ad_id         text,
  ad_name       text,
  spend         numeric(12,2) not null default 0,
  impressions   bigint not null default 0,
  reach         bigint not null default 0,
  frequency     numeric(8,4),
  clicks        bigint not null default 0,
  ctr           numeric(8,4),
  cpm           numeric(10,4),
  leads         integer not null default 0,
  cpl           numeric(10,2),
  cost_per_action_type      jsonb not null default '{}'::jsonb,
  quality_ranking           text,
  engagement_rate_ranking   text,
  synced_at     timestamptz not null default now(),
  unique (account_id, date, ad_id)
);
create index on public.meta_insights_daily (account_id, date desc);

-- ---------------------------------------------------------------------------
-- Metricool (phase 6)
-- ---------------------------------------------------------------------------
create table public.metricool_daily (
  id              uuid primary key default gen_random_uuid(),
  brand_id        text not null,
  date            date not null,
  views           bigint not null default 0,
  reach           bigint not null default 0,
  engagement_rate numeric(8,4),
  saves           integer not null default 0,
  shares          integer not null default 0,
  followers       integer,
  synced_at       timestamptz not null default now(),
  unique (brand_id, date)
);

create table public.metricool_posts (
  id           uuid primary key default gen_random_uuid(),
  brand_id     text not null,
  post_id      text not null,
  published_at timestamptz,
  permalink    text,
  caption      text,
  views        bigint not null default 0,
  reach        bigint not null default 0,
  engagement   numeric(12,2) not null default 0,
  saves        integer not null default 0,
  shares       integer not null default 0,
  synced_at    timestamptz not null default now(),
  unique (brand_id, post_id)
);
create index on public.metricool_posts (brand_id, published_at desc);

-- ---------------------------------------------------------------------------
-- fathom_calls (phase 8)
-- ---------------------------------------------------------------------------
create table public.fathom_calls (
  id             uuid primary key default gen_random_uuid(),
  recording_id   text not null unique,
  title          text,
  started_at     timestamptz,
  duration_min   integer,
  classification call_class,
  classification_locked boolean not null default false,  -- true once a human corrects it
  summary        text,
  action_items   jsonb not null default '[]'::jsonb,
  url            text,
  client_id      uuid references public.clients(id) on delete set null,
  synced_at      timestamptz not null default now()
);
create index on public.fathom_calls (started_at desc);

-- ---------------------------------------------------------------------------
-- stripe_payments (phase 7)
-- ---------------------------------------------------------------------------
create table public.stripe_payments (
  id                 uuid primary key default gen_random_uuid(),
  client_id          uuid references public.clients(id) on delete set null,
  stripe_customer_id text,
  invoice_id         text unique,
  amount             numeric(10,2) not null default 0,
  currency           text not null default 'usd',
  status             text not null,
  paid_at            timestamptz,
  due_at             timestamptz,
  synced_at          timestamptz not null default now()
);
create index on public.stripe_payments (client_id, paid_at desc);

-- ---------------------------------------------------------------------------
-- calendar_events (phase 9)
-- ---------------------------------------------------------------------------
create table public.calendar_events (
  id          uuid primary key default gen_random_uuid(),
  external_id text not null unique,
  title       text,
  starts_at   timestamptz not null,
  ends_at     timestamptz,
  attendees   jsonb not null default '[]'::jsonb,
  link        text,
  synced_at   timestamptz not null default now()
);
create index on public.calendar_events (starts_at);

-- ---------------------------------------------------------------------------
-- notion_client_status (phase 10)
-- ---------------------------------------------------------------------------
create table public.notion_client_status (
  id             uuid primary key default gen_random_uuid(),
  client_id      uuid references public.clients(id) on delete set null,
  page_id        text not null unique,
  title          text,
  status         text,
  excerpt        text,
  last_edited_at timestamptz,
  synced_at      timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- sync_runs — drives every "last updated" label and the 24h stale badge
-- ---------------------------------------------------------------------------
create table public.sync_runs (
  id           uuid primary key default gen_random_uuid(),
  source       text not null,                     -- 'meta' | 'ghl' | 'metricool' | ...
  account_ref  text,                              -- account/brand id, null = whole source
  started_at   timestamptz not null default now(),
  finished_at  timestamptz,
  status       sync_status not null default 'running',
  rows_written integer not null default 0,
  error        text,
  triggered_by text not null default 'cron'       -- 'cron' | 'manual'
);
create index on public.sync_runs (source, started_at desc);

-- Latest successful run per source, for the freshness indicator.
create view public.sync_freshness as
select distinct on (source)
  source,
  finished_at as last_success_at,
  rows_written,
  triggered_by,
  (now() - finished_at) > interval '24 hours' as is_stale
from public.sync_runs
where status = 'success' and finished_at is not null
order by source, finished_at desc;

-- ---------------------------------------------------------------------------
-- quick_actions — audit trail for mark-done / add-note / flag-at-risk
-- ---------------------------------------------------------------------------
create table public.quick_actions (
  id           uuid primary key default gen_random_uuid(),
  actor        uuid references public.profiles(id) on delete set null,
  kind         text not null,
  target_table text,
  target_id    uuid,
  payload      jsonb not null default '{}'::jsonb,
  created_at   timestamptz not null default now()
);
create index on public.quick_actions (created_at desc);

-- ---------------------------------------------------------------------------
-- updated_at triggers
-- ---------------------------------------------------------------------------

create trigger touch_profiles before update on public.profiles
  for each row execute function public.touch_updated_at();
create trigger touch_clients before update on public.clients
  for each row execute function public.touch_updated_at();
create trigger touch_onboarding_checklist before update on public.onboarding_checklist
  for each row execute function public.touch_updated_at();
create trigger touch_content_pipeline before update on public.content_pipeline
  for each row execute function public.touch_updated_at();
create trigger touch_weekly_metrics before update on public.weekly_metrics
  for each row execute function public.touch_updated_at();
create trigger touch_expenses before update on public.expenses
  for each row execute function public.touch_updated_at();
create trigger touch_sales_pipeline before update on public.sales_pipeline
  for each row execute function public.touch_updated_at();
create trigger touch_team_assignments before update on public.team_assignments
  for each row execute function public.touch_updated_at();
create trigger touch_lead_response_log before update on public.lead_response_log
  for each row execute function public.touch_updated_at();
create trigger touch_client_communication_log before update on public.client_communication_log
  for each row execute function public.touch_updated_at();
create trigger touch_ad_accounts before update on public.ad_accounts
  for each row execute function public.touch_updated_at();
-- NevadoMedia BI Dashboard — Row Level Security
-- Run after 0001_schema.sql.
--
-- Model:
--   admin    (Sebastian) — everything.
--   operator (Nico)      — operations only. No retainer amounts, no expenses,
--                          no Stripe, no weekly revenue.
--   anon                 — nothing, except inserting its own funnel events.
--   service_role         — bypasses RLS entirely; used only by the VPS worker.

-- ---------------------------------------------------------------------------
-- Role helpers. SECURITY DEFINER so that reading profiles inside a profiles
-- policy does not recurse.
-- ---------------------------------------------------------------------------
create or replace function public.current_app_role()
returns user_role
language sql
stable
security definer
set search_path = public
as ' select role from public.profiles where id = auth.uid() ';

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as ' select coalesce(public.current_app_role() = ''admin'', false) ';

create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as ' select public.current_app_role() is not null ';

grant execute on function public.current_app_role() to authenticated;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.is_staff() to authenticated;

-- ---------------------------------------------------------------------------
-- Enable RLS everywhere. Default-deny: a table with RLS on and no matching
-- policy returns zero rows.
-- ---------------------------------------------------------------------------


alter table public.profiles enable row level security;
alter table public.profiles force row level security;
alter table public.clients enable row level security;
alter table public.clients force row level security;
alter table public.onboarding_checklist enable row level security;
alter table public.onboarding_checklist force row level security;
alter table public.content_pipeline enable row level security;
alter table public.content_pipeline force row level security;
alter table public.weekly_metrics enable row level security;
alter table public.weekly_metrics force row level security;
alter table public.expenses enable row level security;
alter table public.expenses force row level security;
alter table public.sales_pipeline enable row level security;
alter table public.sales_pipeline force row level security;
alter table public.team_assignments enable row level security;
alter table public.team_assignments force row level security;
alter table public.lead_response_log enable row level security;
alter table public.lead_response_log force row level security;
alter table public.client_communication_log enable row level security;
alter table public.client_communication_log force row level security;
alter table public.funnel_events enable row level security;
alter table public.funnel_events force row level security;
alter table public.ad_accounts enable row level security;
alter table public.ad_accounts force row level security;
alter table public.meta_insights_daily enable row level security;
alter table public.meta_insights_daily force row level security;
alter table public.metricool_daily enable row level security;
alter table public.metricool_daily force row level security;
alter table public.metricool_posts enable row level security;
alter table public.metricool_posts force row level security;
alter table public.fathom_calls enable row level security;
alter table public.fathom_calls force row level security;
alter table public.stripe_payments enable row level security;
alter table public.stripe_payments force row level security;
alter table public.calendar_events enable row level security;
alter table public.calendar_events force row level security;
alter table public.notion_client_status enable row level security;
alter table public.notion_client_status force row level security;
alter table public.sync_runs enable row level security;
alter table public.sync_runs force row level security;
alter table public.quick_actions enable row level security;
alter table public.quick_actions force row level security;

-- ---------------------------------------------------------------------------
-- profiles
-- ---------------------------------------------------------------------------
create policy "read own profile" on public.profiles
  for select to authenticated using (id = auth.uid());

create policy "admin reads all profiles" on public.profiles
  for select to authenticated using (public.is_admin());

create policy "admin writes profiles" on public.profiles
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ---------------------------------------------------------------------------
-- Admin-only tables (money)
-- ---------------------------------------------------------------------------


create policy "admin only" on public.clients
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());
create policy "admin only" on public.expenses
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());
create policy "admin only" on public.weekly_metrics
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());
create policy "admin only" on public.stripe_payments
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- Operators reach clients through this column-filtered view instead. The view
-- runs with the owner's rights, so it is not blocked by the policy above, and
-- because it is a simple view it is auto-updatable — an operator can edit the
-- operational columns and cannot see or touch the financial ones.
create view public.clients_ops
with (security_barrier) as
select
  id, name, service, contract_start, renewal_date, last_touchpoint,
  next_action, next_action_due, goals, goal_progress, at_risk, notes,
  ball_side, location, active, created_at, updated_at
from public.clients;

-- Supabase's default privileges grant ALL on every new object in `public` to
-- anon and authenticated, so the grant below must be preceded by a revoke —
-- otherwise an operator could INSERT and DELETE client rows through the view.
revoke all on public.clients_ops from anon, authenticated;
grant select, update on public.clients_ops to authenticated;

-- ---------------------------------------------------------------------------
-- Operational tables — both roles read and write
-- ---------------------------------------------------------------------------


create policy "staff read" on public.onboarding_checklist for select to authenticated
  using (public.is_staff());
create policy "staff write" on public.onboarding_checklist for all to authenticated
  using (public.is_staff()) with check (public.is_staff());
create policy "staff read" on public.content_pipeline for select to authenticated
  using (public.is_staff());
create policy "staff write" on public.content_pipeline for all to authenticated
  using (public.is_staff()) with check (public.is_staff());
create policy "staff read" on public.sales_pipeline for select to authenticated
  using (public.is_staff());
create policy "staff write" on public.sales_pipeline for all to authenticated
  using (public.is_staff()) with check (public.is_staff());
create policy "staff read" on public.team_assignments for select to authenticated
  using (public.is_staff());
create policy "staff write" on public.team_assignments for all to authenticated
  using (public.is_staff()) with check (public.is_staff());
create policy "staff read" on public.lead_response_log for select to authenticated
  using (public.is_staff());
create policy "staff write" on public.lead_response_log for all to authenticated
  using (public.is_staff()) with check (public.is_staff());
create policy "staff read" on public.client_communication_log for select to authenticated
  using (public.is_staff());
create policy "staff write" on public.client_communication_log for all to authenticated
  using (public.is_staff()) with check (public.is_staff());
create policy "staff read" on public.quick_actions for select to authenticated
  using (public.is_staff());
create policy "staff write" on public.quick_actions for all to authenticated
  using (public.is_staff()) with check (public.is_staff());

-- ---------------------------------------------------------------------------
-- Synced tables — staff read, worker writes with service_role
-- ---------------------------------------------------------------------------


create policy "staff read" on public.ad_accounts for select to authenticated
  using (public.is_staff());
create policy "staff read" on public.meta_insights_daily for select to authenticated
  using (public.is_staff());
create policy "staff read" on public.metricool_daily for select to authenticated
  using (public.is_staff());
create policy "staff read" on public.metricool_posts for select to authenticated
  using (public.is_staff());
create policy "staff read" on public.fathom_calls for select to authenticated
  using (public.is_staff());
create policy "staff read" on public.calendar_events for select to authenticated
  using (public.is_staff());
create policy "staff read" on public.notion_client_status for select to authenticated
  using (public.is_staff());
create policy "staff read" on public.sync_runs for select to authenticated
  using (public.is_staff());

-- Two exceptions where a human edits synced data by hand.
create policy "admin edits ad accounts" on public.ad_accounts
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Correcting a Fathom auto-classification must stick across re-syncs.
create policy "staff reclassifies calls" on public.fathom_calls
  for update to authenticated
  using (public.is_staff()) with check (public.is_staff());

-- ---------------------------------------------------------------------------
-- funnel_events — the public landing page writes here anonymously
-- ---------------------------------------------------------------------------
create policy "staff read funnel" on public.funnel_events
  for select to authenticated using (public.is_staff());

-- Anonymous visitors may only append, never read back.
create policy "visitor appends funnel event" on public.funnel_events
  for insert to anon with check (
    session_id is not null and length(session_id) between 8 and 64
  );

-- ---------------------------------------------------------------------------
-- sync_freshness view inherits sync_runs' policy through the base table.
-- ---------------------------------------------------------------------------
alter view public.sync_freshness set (security_invoker = true);
revoke all on public.sync_freshness from anon, authenticated;
grant select on public.sync_freshness to authenticated;
-- Phase 3 additions: things the manual-input sections need that phase 1 did not
-- anticipate. Run after 0002_rls.sql.

-- ---------------------------------------------------------------------------
-- When a client relationship ended. Churn is "lost this month vs signed this
-- month", and without this there is no way to date a loss — `active` alone
-- says the state, not when it changed.
-- ---------------------------------------------------------------------------
alter table public.clients add column if not exists ended_at date;

-- ---------------------------------------------------------------------------
-- app_settings — small admin-owned key/value store. Revenue per head needs a
-- team headcount, which belongs to nobody else's table.
-- ---------------------------------------------------------------------------
create table if not exists public.app_settings (
  key        text primary key,
  value      jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.app_settings enable row level security;
alter table public.app_settings force row level security;

create policy "admin manages settings" on public.app_settings
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

create trigger touch_app_settings before update on public.app_settings
  for each row execute function public.touch_updated_at();

insert into public.app_settings (key, value) values
  ('team_size', '3'::jsonb)
on conflict (key) do nothing;

-- ---------------------------------------------------------------------------
-- Operators need to read the content pipeline's client colour coding, which
-- means reading client names — already available through clients_ops.
-- Nothing further required.
-- ---------------------------------------------------------------------------

-- NevadoMedia BI Dashboard — seed data
-- Idempotent: safe to re-run. Run after 0002_rls.sql.

-- ---------------------------------------------------------------------------
